version: '3.8'

services:
  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - web
    networks:
      - frontend
      - backend
    restart: always

  # API service
  api:
    build:
      context: ./api
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres_password
      - DB_NAME=breachdb
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
    networks:
      - backend
      - frontend
    restart: unless-stopped

  # PostgreSQL database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=breachdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis cache
  cache:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Web frontend
  web:
    build:
      context: ./web
    environment:
      - API_URL=http://api:8080
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - frontend
      - backend
    restart: unless-stopped

networks:
  frontend:
  backend:

volumes:
  postgres_data:
  redis_data: 