name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Test API
      run: |
        cd api
        go test -v ./...
    
    - name: Test Web
      run: |
        cd web
        go test -v ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build API image
      uses: docker/build-push-action@v4
      with:
        context: ./api
        push: false
        tags: breach-checker-api:latest
    
    - name: Build Web image
      uses: docker/build-push-action@v4
      with:
        context: ./web
        push: false
        tags: breach-checker-web:latest
    
    - name: Build Nginx image
      uses: docker/build-push-action@v4
      with:
        context: ./nginx
        push: false
        tags: breach-checker-nginx:latest